configuration: CI

version: 1.6.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
 - nuget restore

build:
  verbosity: minimal

after_test:
 - ps: .\nuget\pack-language-ext.ps1
 - ps: .\nuget\pack-language-ext-process.ps1
 - ps: .\nuget\pack-language-ext-process-redis.ps1

deploy:
  provider: NuGet
  api_key:
    secure: PmMMAd8abwpwcaFTVXd5l8GSz/x8beDrCC3ndZeBHnQFzHRW7eJK+OgDP9CInUts
  artifact: /.*\.nupkg/

