version: 1.7.5.{build}
os: Previous Visual Studio 2015 RC
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_test:
- cmd: xunit.console.clr4 <assembly> /appveyor

